GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/62e92479003bccf6edb6bf82

###

DELETE http://localhost:3001/api/persons/62eea0d2cfdd84286c0dcc88

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test content 3",
    "number": "05-777777"
}