GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/62e92479003bccf6edb6bf82

###

DELETE http://localhost:3001/api/persons/62eb95fd8405a1cb0fd358a2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test content 2",
    "number": "050-777-9990"
}